### ISSUE TITLE
TableColumn / Status not backwards compatible in 1.2

### ISSUE THREAD

**Issue by romaninsh** [atk4/ui#229]
Since upgrade to 1.2 this error appeared:

ArgumentCountError: Too few arguments to function atk4\ui\TableColumn\Status::__construct(), 0 passed in /app/vendor/atk4/core/src/FactoryTrait.php on line 152 and exactly 1 expected (in /app/vendor/atk4/ui/src/TableColumn/Status.php:24)

This is a regular "boolean" column.

**Comment by slava-vishnyakov** [comment]
👍  Excellent, works now! Thanks!

**Comment by slava-vishnyakov** [comment]
Although, clicking on "show" gets another error now:
https://atk-warehouse.herokuapp.com/docs.php?type=purchase&id=92

![image](https://user-images.githubusercontent.com/817931/31562241-58d40e36-b063-11e7-9867-6d9c8c646e74.png)

**Comment by slava-vishnyakov** [comment]
And also clicking "Internal" fails:
https://atk-warehouse.herokuapp.com/production.php

![image](https://user-images.githubusercontent.com/817931/31562283-810301a0-b063-11e7-8725-2339ab2d6fdb.png)
